import { Public_Sans } from "next/font/google";
import "@/styles/globals.scss";
import ThemeRegistry from "@/components/ThemeRegistry";
import MainLayout from "@/components/MainLayout";
import LocalizationProviderWrapper from "@/components/LocalizationProviderWrapper";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={publicSans.variable}>
        <LocalizationProviderWrapper>
          <ThemeRegistry>
            <MainLayout>
              {children}
            </MainLayout>
          </ThemeRegistry>
        </LocalizationProviderWrapper>
      </body>
    </html>
  );
}
